#+STARTUP: hidestars showall
* conjecture
  A ~clojure.test~ compatible third-party testing library for Clojure.  Please
  contribute code and features through GitHub issues and pull requests.
** Usage
   Same as ~clojure.test~, except you pull in ~name.stadig.conjecture~.

   For example, you would add the following dependency to your project.clj:

   : :dependencies [[name.stadig/conjecture "0.2.0-SNAPSHOT"]]

   Use ~name.stadig.conjecture~ in your tests:

   : (ns foo.bar.test
   :   (:use [name.stadig.conjecture]))
   :
   : (deftest test-widget
   :   (is (= foo bar))
   :   ...)

   Conjecture is compatible with any ~clojure.test~ based tests you may have.
   You simply swap ~name.stadig.conjecture~ in for ~clojure.test~.

   You can add the lein-conjecture plugin to your project.clj, if that's your
   style:

   : :plugins [[name.stadig/lein-conjecture "0.1.0"]]

   With this plugin you can run your tests with ~lein conjecture~, or if your
   muscle memory is too overwhelming, you can add an alias to your project.clj:

   : :aliases {"test" "conjecture"}

   Now you can run your tests with ~lein test~.

   You can see examples of all of this by looking at the project.clj for this
   project.
** Documentation
   You will find documentation in the [[doc]] folder.

   Documentation contributions are welcomed.  You may use GitHub issues and pull
   requests to help with documentation.
** Known Issues
   - Any tools that depend directly on ~clojure.test~ will not be compatible,
     since the namespace is different for conjecture (for example,
     clojure-test-mode will run the tests, but report incorrectly).
** Differences from clojure.test
   - Adds support for creating idempotent fixtures.
   - Runs fixtures when you call a function as a test (e.g. at a REPL)

   See CHANGELOG.org for more details.
** License
   : Copyright © Rich Hickey and Paul Stadig. All rights reserved.
   :
   : The use and distribution terms for this software are covered by the Eclipse
   : Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php) which
   : can be found in the file epl-v10.html at the root of this distribution.
   :
   : By using this software in any fashion, you are agreeing to be bound by the
   : terms of this license.
   :
   : You must not remove this notice, or any other, from this software.
